<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Booking_model extends CI_Model
{

    public $table = 'booking';
    public $id = 'id_book';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('a.id_book,a.email,a.tanggal,a.nomor_booking,a.meja,a.id_restoran,a.status,b.nama');
        $this->datatables->from('booking a');
        $this->datatables->where('id_restoran', $this->session->userdata('id_restoran'));
        //add this line for join
        $this->datatables->join('tbl_user_mobile b', 'a.email = b.email');
        $this->datatables->add_column('action', anchor(site_url('booking/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('booking/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('booking/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_book');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_book', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('nomor_booking', $q);
	$this->db->or_like('meja', $q);
	$this->db->or_like('id_restoran', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_book', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('nomor_booking', $q);
	$this->db->or_like('meja', $q);
	$this->db->or_like('id_restoran', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Booking_model.php */
/* Location: ./application/models/Booking_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-09-01 21:05:55 */
/* http://harviacode.com */